import { useState } from "react";
import { format, parseISO, addMonths } from "date-fns";
import { CalendarPlus, Repeat, X } from "lucide-react";
import { REPEAT_OPTIONS, repeatDates, type RepeatFrequency } from "@/lib/marketing";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export interface EventDates { start: string; end: string; extra: string[] }

/**
 * Event dates: a start (and optional end for a multi-day run), plus any number of extra days.
 * Extra days can be added one at a time or generated by a repeat rule (weekly, monthly, …).
 */
export function EventDatesEditor({ value, onChange }: { value: EventDates; onChange: (v: EventDates) => void }) {
  const [oneDate, setOneDate] = useState("");
  const [freq, setFreq] = useState<RepeatFrequency>("weekly");
  const [until, setUntil] = useState("");
  const [showRepeat, setShowRepeat] = useState(false);

  const extra = Array.from(new Set(value.extra)).filter((d) => d && d !== value.start).sort();
  const setExtra = (list: string[]) => onChange({ ...value, extra: Array.from(new Set(list)).filter((d) => d && d !== value.start).sort() });
  const defaultUntil = value.start ? format(addMonths(parseISO(value.start), 3), "yyyy-MM-dd") : "";
  const untilValue = until || defaultUntil;
  const preview = value.start && untilValue ? repeatDates(value.start, freq, untilValue) : [];

  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label htmlFor="evt-start">Event start</Label>
          <Input id="evt-start" type="date" value={value.start} onChange={(e) => e.target.value && onChange({ ...value, start: e.target.value })} className="mt-1" />
        </div>
        <div>
          <Label htmlFor="evt-end">Event end <span className="text-muted-foreground font-normal">(if it runs several days in a row)</span></Label>
          <Input id="evt-end" type="date" value={value.end} min={value.start} onChange={(e) => onChange({ ...value, end: e.target.value })} className="mt-1" />
        </div>
      </div>

      <div className="rounded-md border bg-muted/20 p-3 space-y-3">
        <div className="flex items-center justify-between gap-2">
          <div className="text-sm font-medium">More dates <span className="font-normal text-muted-foreground">(other days this event happens)</span></div>
          {extra.length > 0 && (
            <button type="button" className="text-xs text-primary hover:underline shrink-0" onClick={() => setExtra([])}>Clear all</button>
          )}
        </div>

        {extra.length > 0 ? (
          <div className="flex flex-wrap gap-1.5 max-h-28 overflow-y-auto">
            {extra.map((d) => (
              <span key={d} className="inline-flex items-center gap-1 rounded-full border bg-background pl-2.5 pr-1 py-0.5 text-xs">
                {format(parseISO(d), "EEE, MMM d")}
                <button type="button" aria-label={`Remove ${format(parseISO(d), "MMM d")}`} className="rounded-full p-0.5 text-muted-foreground hover:text-destructive hover:bg-muted"
                  onClick={() => setExtra(extra.filter((x) => x !== d))}>
                  <X className="w-3 h-3" />
                </button>
              </span>
            ))}
          </div>
        ) : (
          <p className="text-xs text-muted-foreground">Just the one date so far. Add single days, or set it to repeat.</p>
        )}

        <div className="flex flex-wrap items-end gap-2">
          <div>
            <Label htmlFor="evt-add" className="text-xs">Add a day</Label>
            <Input id="evt-add" type="date" value={oneDate} onChange={(e) => setOneDate(e.target.value)} className="mt-1 h-8 text-xs w-[150px]" />
          </div>
          <Button type="button" variant="outline" size="sm" className="h-8" disabled={!oneDate}
            onClick={() => { setExtra([...extra, oneDate]); setOneDate(""); }}>
            <CalendarPlus className="w-3.5 h-3.5 mr-1.5" /> Add
          </Button>
          <Button type="button" variant={showRepeat ? "secondary" : "outline"} size="sm" className="h-8" onClick={() => setShowRepeat((v) => !v)}>
            <Repeat className="w-3.5 h-3.5 mr-1.5" /> Repeat…
          </Button>
        </div>

        {showRepeat && (
          <div className="rounded-md border bg-background p-3 space-y-2">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <div>
                <Label className="text-xs">How often</Label>
                <Select value={freq} onValueChange={(v) => setFreq(v as RepeatFrequency)}>
                  <SelectTrigger className="mt-1 h-8 text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {REPEAT_OPTIONS.map((o) => <SelectItem key={o.id} value={o.id}>{o.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="evt-until" className="text-xs">Until</Label>
                <Input id="evt-until" type="date" value={untilValue} min={value.start} onChange={(e) => setUntil(e.target.value)} className="mt-1 h-8 text-xs" />
              </div>
            </div>
            <div className="flex items-center justify-between gap-2">
              <p className="text-xs text-muted-foreground">
                {preview.length === 0
                  ? "No dates in that range."
                  : `Adds ${preview.length} date${preview.length === 1 ? "" : "s"}: ${preview.slice(0, 3).map((d) => format(parseISO(d), "MMM d")).join(", ")}${preview.length > 3 ? ` … ${format(parseISO(preview[preview.length - 1]), "MMM d")}` : ""}`}
              </p>
              <Button type="button" size="sm" className="h-8 shrink-0" disabled={preview.length === 0}
                onClick={() => { setExtra([...extra, ...preview]); setShowRepeat(false); }}>
                Add these dates
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
