// Generated by vibe — do not edit. Values are materialized per-project from connector state.
export const vibeConfig = {
  project: {
    environment: "prod",
    namespace: "AG-D5HZKZ2TNH",
    projectId: "6c9fc416-c440-4bad-a4ac-274e11e95763",
    partnerId: "RZG9",
  },
  sso: {
    clientId: "77c36b5a-d90a-4d6e-841e-8a3e28aa5f70",
    authority: "https://iam-prod.apigateway.co",
    scopes: "business-app openid profile user:read",
    loginParamKey: "account_id",
    loginParamValue: "AG-D5HZKZ2TNH",
    accessCheckUrl: "https://vibe-prod.apigateway.co/api/projects/AG-D5HZKZ2TNH/6c9fc416-c440-4bad-a4ac-274e11e95763/access",
    signoutNamespace: "RZG9",
  },
  analytics: {
    queryMetricsUrl: "",
  },
  supabase: {
    url: "https://tsrnpmkipdbtwyrlfbuy.supabase.co",
    publishableKey: "sb_publishable_UMd0Ij8NxKSCoP_13XA3vQ_58KxPUOP",
  },
  crm: {
    apiBaseUrl: "",
  },
  businessnav: {
    scriptUrl: "",
    partnerId: "",
    marketId: "",
    accountId: "",
  },
} as const;
